# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_test_card.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(316, 476)
        Frame.setStyleSheet("QFrame{\n"
"    background-color:#0A2647;\n"
"    color: beige;\n"
"    padding: 4px;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Frame)
        self.gridLayout.setObjectName("gridLayout")
        self.slot1 = QtWidgets.QFrame(Frame)
        self.slot1.setStyleSheet("QFrame{\n"
"    background-color:#0A2647;\n"
"    color: beige;\n"
"    border: 0px;\n"
"}")
        self.slot1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.slot1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.slot1.setObjectName("slot1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.slot1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(69, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        self.add_btn = QtWidgets.QPushButton(self.slot1)
        self.add_btn.setMaximumSize(QtCore.QSize(66, 61))
        font = QtGui.QFont()
        font.setFamily("Rasa SemiBold")
        font.setPointSize(65)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.add_btn.setFont(font)
        self.add_btn.setStyleSheet("QPushButton{\n"
"    background-color: #0A2647;\n"
"    border-color: #7F8487;\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 30px;\n"
"    padding: 10px;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-color: #7289DA ;\n"
"    color: white;\n"
"\n"
"}")
        self.add_btn.setObjectName("add_btn")
        self.gridLayout_2.addWidget(self.add_btn, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.slot1, 0, 0, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.add_btn.setText(_translate("Frame", "+"))


class AddTestCard(Ui_Frame): 
    '''this classes adds the page switching funcitonality to the generated code
       The follwing class implements the TestCars Ui frame.'''
    
    def setupUi(self, Form, stackedWidget):
        ''' this function gets the stacked widget and changes 
        the shown page according to the events in the page '''
        
        super().setupUi(Form)
        
        # define stack widget as a class property that is accessible within the class 
        self.stackedWidget = stackedWidget

        # 'Register here'  button event that switches the login page to register page
        self.add_btn.clicked.connect(lambda: self.switch_to_create())


    def switch_to_create(self):
        ''' this function switches to register page from login page''' 
        self.stackedWidget.setCurrentIndex(1)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
