# -*- coding: utf-8 -*-

# Form impementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import resources
from PyQt5 import QtCore, QtGui, QtWidgets

# import pages
from sign_in import Login 
from register import Register


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        MainWindow.resize(1040, 681)
        self.centralwidget.setObjectName("centralwidget")
        
        # define the stack of widgets 
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(-1, -1, 1040, 681))
        self.stackedWidget.setObjectName("stackedWidget")
       
        ''' Here we define the imported pages and add them to the stack of widgets'''
        
        # login page 
        self.login = QtWidgets.QWidget()
        ui = Login()
        ui.setupUi(self.login, self.stackedWidget)
        self.login.setObjectName("login")
        self.stackedWidget.addWidget(self.login)


        # register page 
        self.register = QtWidgets.QWidget()
        ui = Register()
        ui.setupUi(self.register, self.stackedWidget)
        self.register.setObjectName("register")
        self.stackedWidget.addWidget(self.register)
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
