# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my_tests1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1097, 663)
        Form.setStyleSheet("background-color:#2C2F33;")
        self.frame_10 = QtWidgets.QFrame(Form)
        self.frame_10.setGeometry(QtCore.QRect(120, 170, 881, 391))
        self.frame_10.setStyleSheet("QFrame{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    padding: 6px;    \n"
"    background-color: #23272a;\n"
"    botder: 1px solid white;\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setStyleSheet("QFrame{\n"
"    background-color: #4b4b4b;\n"
"    color: beige;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 4px;\n"
"    border-color:beige;\n"
"    padding: 4px;\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setStyleSheet("color:beige;\n"
"background-color: #2D033B;\n"
"border: 1px solid beige;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("URW Bookman [UKWN]")
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QFrame{\n"
"    border: 0px;\n"
"}")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        self.frame_13.setStyleSheet("border:1px solid beige;\n"
"background-color: #453C67;\n"
"color:black;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setStyleSheet("color:beige;\n"
"border: 0px solid beige;")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.label_8 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("URW Bookman [UKWN]")
        font.setPointSize(17)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border:0px;\n"
"")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.verticalLayout_6.addWidget(self.frame_14)
        self.label_10 = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setFamily("URW Bookman [UKWN]")
        font.setPointSize(17)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("border:0px;\n"
"color:white;")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.frame_15 = QtWidgets.QFrame(self.frame_13)
        self.frame_15.setStyleSheet("\n"
"border: 0px solid beige;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: #afafaf;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    padding: 6px;\n"
"\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_8.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: #777777;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_8.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    background-color: #ff4b4b;\n"
"    color: black;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_8.addWidget(self.pushButton_9)
        self.verticalLayout_6.addWidget(self.frame_15)
        self.verticalLayout_5.addWidget(self.frame_13)
        self.horizontalLayout_3.addWidget(self.frame_11)
        self.frame_16 = QtWidgets.QFrame(self.frame_10)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_10.setGeometry(QtCore.QRect(60, 160, 66, 61))
        font = QtGui.QFont()
        font.setFamily("Rasa SemiBold")
        font.setPointSize(65)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("    background-color: #7289da;\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 30px;\n"
"    border-color: #23272a;\n"
"    padding: 10px;\n"
"    color: #ffffff;")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_3.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.frame_10)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_11.setGeometry(QtCore.QRect(60, 150, 66, 61))
        font = QtGui.QFont()
        font.setFamily("Rasa SemiBold")
        font.setPointSize(65)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("    background-color: #7289da;\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 30px;\n"
"    border-color: #23272a;\n"
"    padding: 10px;\n"
"    color: #ffffff;")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_3.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.frame_10)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_12.setGeometry(QtCore.QRect(60, 150, 66, 61))
        font = QtGui.QFont()
        font.setFamily("Rasa SemiBold")
        font.setPointSize(65)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("    background-color: #7289da;\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 30px;\n"
"    border-color: #23272a;\n"
"    padding: 10px;\n"
"    color: #ffffff;")
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_3.addWidget(self.frame_18)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(440, 90, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(26)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: white;")
        self.label_11.setObjectName("label_11")
        self.pushButton_14 = QtWidgets.QPushButton(Form)
        self.pushButton_14.setGeometry(QtCore.QRect(20, 300, 81, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.pushButton_14.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"    background-color: #2C2F33;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    padding: 0px;\n"
"}")
        self.pushButton_14.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon)
        self.pushButton_14.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_13 = QtWidgets.QPushButton(Form)
        self.pushButton_13.setGeometry(QtCore.QRect(1010, 310, 141, 74))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_13.setAutoFillBackground(False)
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"    background-color: #FED049;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QPushButton:onclick{\n"
"    background-color: #ffff;\n"
"}\n"
"    ")
        self.pushButton_13.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/next2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_13.setIcon(icon1)
        self.pushButton_13.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_13.setObjectName("pushButton_13")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_7.setText(_translate("Form", "English"))
        self.label_8.setText(_translate("Form", "Grade 11"))
        self.label_10.setText(_translate("Form", "Present Simple"))
        self.pushButton_7.setText(_translate("Form", "Start"))
        self.pushButton_8.setText(_translate("Form", "Upload"))
        self.pushButton_9.setText(_translate("Form", "Remove"))
        self.pushButton_10.setText(_translate("Form", "+"))
        self.pushButton_11.setText(_translate("Form", "+"))
        self.pushButton_12.setText(_translate("Form", "+"))
        self.label_11.setText(_translate("Form", "My Tests"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
