# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_in.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import resources
from PyQt5 import QtCore, QtGui, QtWidgets
import requests
import register 

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1040, 682)
        MainWindow.setMinimumSize(QtCore.QSize(1040, 682))
        MainWindow.setMaximumSize(QtCore.QSize(1040, 682))
        font = QtGui.QFont()
        font.setFamily("Rekha")
        font.setPointSize(30)
        font.setItalic(False)
        font.setStrikeOut(False)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color:#2C2F33;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(400, 140, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(26)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;")
        self.label_3.setObjectName("label_3")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(310, 210, 301, 251))
        self.frame_2.setStyleSheet("background-color: #23272A;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.pswd = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pswd.setFont(font)
        self.pswd.setStyleSheet("QLineEdit{\n"
"    color:white;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 1px solid rgb(170, 255, 0)  ;\n"
"}")
        self.pswd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pswd.setObjectName("pswd")
        self.gridLayout.addWidget(self.pswd, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("padmaa")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.id = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.id.setFont(font)
        self.id.setStyleSheet("QLineEdit{\n"
"    color:white;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 1px solid rgb(170, 255, 0)  ;\n"
"}")
        self.id.setText("")
        self.id.setObjectName("id")
        self.gridLayout.addWidget(self.id, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("padmaa")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: white;")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_3, 0, 0, 1, 1)
        self.submit_btn = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.submit_btn.setFont(font)
        self.submit_btn.setStyleSheet("QPushButton{\n"
"    background-color: #FED049;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"        background-color: #7289DA;\n"
"        color: white;\n"
"}")
        self.submit_btn.setObjectName("submit_btn")
        self.gridLayout_2.addWidget(self.submit_btn, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(590, 210, 441, 461))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(-130, -160, 371, 321))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(-120, 260, 411, 401))
        self.label_5.setObjectName("label_5")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(310, 470, 198, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: white;")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(500, 470, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: #7289da;")
        self.label_12.setObjectName("label_12")
        self.label_5.raise_()
        self.label_11.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.frame_2.raise_()
        self.label_4.raise_()
        self.label_12.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Sign In"))
        self.label.setText(_translate("MainWindow", "Password"))
        self.label_7.setText(_translate("MainWindow", "ID"))
        self.submit_btn.setText(_translate("MainWindow", "Login"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/illustrations/imgs/2.png\"/></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/illustrations/imgs/6.png\"/></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/illustrations/imgs/7.png\"/></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "Don\'t have an account? "))
        self.label_12.setText(_translate("MainWindow", "Register  here"))


        # submit button click event hooking 
        #self.submit_btn.clicked.connect(self.submit_form)

    # this function will be called when the submit button is clicked 
    def submit_form(self):
        '''
        print("hi")
        self.submit_btn.setStyleSheet("QPushButton{\n"
                                        "    background-color: #EF9A53;\n"
                                        "    color: white;\n"
                                        "    border-style: outset;\n"
                                        "    border-width: 2px;\n"
                                        "    border-radius: 10px;\n"
                                        "    border-color: beige;\n"
                                        "    padding: 6px;\n"
                                        "}\n"
                                        "\n")
        
        PARAMS = {
                "password": self.pswd.text(),
                "id": self.id.text()      
        }

        URL = "http://localhost:8080/api/signIn"
        r = requests.post(url = URL, json=PARAMS)
        print(r.text)
        '''

def main():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

if __name__ == "__main__":
    main()
