# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enter_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import resources


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1040, 681)
        Form.setStyleSheet("background-color:#2C2F33;")
        self.label_36 = QtWidgets.QLabel(Form)
        self.label_36.setGeometry(QtCore.QRect(320, 180, 421, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(26)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color: white;")
        self.label_36.setObjectName("label_36")
        self.frame_11 = QtWidgets.QFrame(Form)
        self.frame_11.setGeometry(QtCore.QRect(370, 280, 301, 161))
        self.frame_11.setStyleSheet("background-color: #23272A;\n"
"")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setStyleSheet("")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label_34 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("padmaa")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: white;")
        self.label_34.setObjectName("label_34")
        self.gridLayout_21.addWidget(self.label_34, 1, 0, 1, 1)
        self.token = QtWidgets.QLineEdit(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.token.setFont(font)
        self.token.setStyleSheet("QLineEdit{\n"
"    color:white;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 1px solid rgb(170, 255, 0)  ;\n"
"}")
        self.token.setText("")
        self.token.setObjectName("token")
        self.gridLayout_21.addWidget(self.token, 2, 0, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_21, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.frame_12, 0, 0, 1, 1)
        self.continue_btn = QtWidgets.QPushButton(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.continue_btn.setFont(font)
        self.continue_btn.setStyleSheet("QPushButton{\n"
"    background-color: #FED049;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"        background-color: #7289DA;\n"
"        color: white;\n"
"}")
        self.continue_btn.setObjectName("continue_btn")
        self.gridLayout_19.addWidget(self.continue_btn, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(640, 350, 401, 381))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(-30, 320, 461, 351))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(-50, -160, 341, 441))
        self.label_3.setObjectName("label_3")
        self.label_2.raise_()
        self.label.raise_()
        self.label_36.raise_()
        self.frame_11.raise_()
        self.label_3.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_36.setText(_translate("Form", "Welcome Back Harel"))
        self.label_34.setText(_translate("Form", "Enter Test Token"))
        self.continue_btn.setText(_translate("Form", "Continue "))
        self.label.setText(_translate("Form", "<html><head/><body><p><img src=\":/illustrations/imgs/20.png\"/></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><img src=\":/illustrations/imgs/21.png\"/></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><img src=\":/illustrations/imgs/23.png\"/></p></body></html>"))



class EnterTest(Ui_Form):    
    def setupUi(self, Form, stackedWidget=None):
        ''' this function gets the stacked widget and changes 
        the shown page according to the events in the page '''
        
        super().setupUi(Form)
        
        # define stack widget as a class property that is accessible within the class 
        self.stackedWidget = stackedWidget

        # This button enters to the waiting room
        self.continue_btn.clicked.connect(lambda: self.switch_page())


    def switch_page(self):
        self.stackedWidget.setCurrentIndex(4)
        



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = EnterTest()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
