# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/sign_in.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import resources
from PyQt5 import QtCore, QtGui, QtWidgets
import requests
from PyQt5.QtWidgets import *
from PyQt5 import QtCore, QtGui
from PyQt5.QtGui import *
from PyQt5.QtCore import *

# for JWT storage 
import keyring
import json


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1040, 681)
        Form.setStyleSheet("background-color:#2C2F33;")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(1530, 501, 441, 461))
        self.label_10.setObjectName("label_10")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(1440, 760, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: #7289da;")
        self.label_15.setObjectName("label_15")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(1250, 760, 198, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: white;")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(1340, 430, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(26)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: white;")
        self.label_19.setObjectName("label_19")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(1720, 691, 441, 461))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(1000, 320, 371, 321))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(1010, 740, 411, 401))
        self.label_5.setObjectName("label_5")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(1630, 950, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: #7289da;")
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(1440, 950, 198, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: white;")
        self.label_14.setObjectName("label_14")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(1530, 620, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(26)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: white;")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(1560, 841, 441, 461))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(840, 470, 371, 321))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(850, 890, 411, 401))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(1470, 1100, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: #7289da;")
        self.label_24.setObjectName("label_24")
        self.label_27 = QtWidgets.QLabel(Form)
        self.label_27.setGeometry(QtCore.QRect(1280, 1100, 198, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: white;")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(Form)
        self.label_28.setGeometry(QtCore.QRect(1370, 770, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(26)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: white;")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(Form)
        self.label_29.setGeometry(QtCore.QRect(600, 211, 441, 461))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(Form)
        self.label_30.setGeometry(QtCore.QRect(-120, -160, 371, 321))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(Form)
        self.label_31.setGeometry(QtCore.QRect(-110, 260, 411, 401))
        self.label_31.setObjectName("label_31")
        self.frame_11 = QtWidgets.QFrame(Form)
        self.frame_11.setGeometry(QtCore.QRect(320, 210, 301, 251))
        self.frame_11.setStyleSheet("background-color: #23272A;\n"
"")


        # creating a QGraphicsDropShadowEffect object
        shadow = QGraphicsDropShadowEffect()
        shadow.setBlurRadius(15)
        shadow.setOffset(2, 2)
        shadow.setColor(Qt.black) 
        self.frame_11.setGraphicsEffect(shadow)


        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setStyleSheet("")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)

        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.id = QtWidgets.QLineEdit(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.id.setFont(font)
        self.id.setStyleSheet("QLineEdit{\n"
"    color:white;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 1px solid rgb(170, 255, 0)  ;\n"
"}")
        self.id.setText("")
        self.id.setObjectName("id")
        self.gridLayout_21.addWidget(self.id, 2, 0, 1, 1)
        self.pswd = QtWidgets.QLineEdit(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pswd.setFont(font)
        self.pswd.setStyleSheet("QLineEdit{\n"
"    color:white;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 1px solid rgb(170, 255, 0)  ;\n"
"}")
        self.pswd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pswd.setObjectName("pswd")
        self.gridLayout_21.addWidget(self.pswd, 4, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("padmaa")
        font.setPointSize(13)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color: white;")
        self.label_33.setObjectName("label_33")
        self.gridLayout_21.addWidget(self.label_33, 3, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("padmaa")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: white;")
        self.label_34.setObjectName("label_34")
        self.gridLayout_21.addWidget(self.label_34, 1, 0, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_21, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.frame_12, 0, 0, 1, 1)
        self.submit_btn = QtWidgets.QPushButton(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.submit_btn.setFont(font)
        self.submit_btn.setStyleSheet("QPushButton{\n"
"    background-color: #FED049;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"        background-color: #7289DA;\n"
"        color: white;\n"
"}")
        self.submit_btn.setObjectName("submit_btn")
        self.gridLayout_19.addWidget(self.submit_btn, 1, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(Form)
        self.label_35.setGeometry(QtCore.QRect(320, 470, 198, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: white;")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(Form)
        self.label_36.setGeometry(QtCore.QRect(410, 140, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(26)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color: white;")
        self.label_36.setObjectName("label_36")
        self.btn_switch_register = QtWidgets.QPushButton(Form)
        self.btn_switch_register.setGeometry(QtCore.QRect(498, 463, 117, 33))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_switch_register.setFont(font)
        self.btn_switch_register.setStyleSheet("QPushButton{\n"
"    color: #7289da;\n"
"    background-color:#2C2F33;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    text-decoration: underline;\n"
"}")
        self.btn_switch_register.setFlat(True)
        self.btn_switch_register.setObjectName("btn_switch_register")
        self.label_35.raise_()
        self.label_10.raise_()
        self.label_15.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_12.raise_()
        self.label_14.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_27.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.label_30.raise_()
        self.label_31.raise_()
        self.frame_11.raise_()
        self.label_36.raise_()
        self.btn_switch_register.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p><img src=\":/illustrations/imgs/2.png\"/></p></body></html>"))
        self.label_15.setText(_translate("Form", "Register  here"))
        self.label_18.setText(_translate("Form", "Don\'t have an account? "))
        self.label_19.setText(_translate("Form", "Sign In"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><img src=\":/illustrations/imgs/2.png\"/></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><img src=\":/illustrations/imgs/6.png\"/></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><img src=\":/illustrations/imgs/7.png\"/></p></body></html>"))
        self.label_12.setText(_translate("Form", "Register  here"))
        self.label_14.setText(_translate("Form", "Don\'t have an account? "))
        self.label_20.setText(_translate("Form", "Sign In"))
        self.label_21.setText(_translate("Form", "<html><head/><body><p><img src=\":/illustrations/imgs/2.png\"/></p></body></html>"))
        self.label_22.setText(_translate("Form", "<html><head/><body><p><img src=\":/illustrations/imgs/6.png\"/></p></body></html>"))
        self.label_23.setText(_translate("Form", "<html><head/><body><p><img src=\":/illustrations/imgs/7.png\"/></p></body></html>"))
        self.label_24.setText(_translate("Form", "Register  here"))
        self.label_27.setText(_translate("Form", "Don\'t have an account? "))
        self.label_28.setText(_translate("Form", "Sign In"))
        self.label_29.setText(_translate("Form", "<html><head/><body><p><img src=\":/illustrations/imgs/2.png\"/></p></body></html>"))
        self.label_30.setText(_translate("Form", "<html><head/><body><p><img src=\":/illustrations/imgs/6.png\"/></p></body></html>"))
        self.label_31.setText(_translate("Form", "<html><head/><body><p><img src=\":/illustrations/imgs/7.png\"/></p></body></html>"))
        self.label_33.setText(_translate("Form", "Password"))
        self.label_34.setText(_translate("Form", "ID"))
        self.submit_btn.setText(_translate("Form", "Login"))
        self.label_35.setText(_translate("Form", "Don\'t have an account? "))
        self.label_36.setText(_translate("Form", "Sign In"))
        self.btn_switch_register.setText(_translate("Form", "Register here!"))


class Login(Ui_Form): 
    '''this classes adds the page switching funcitonality to the generated code'''
    
    def setupUi(self, Form, stackedWidget):
        ''' this function gets the stacked widget and changes 
        the shown page according to the events in the page '''
        
        super().setupUi(Form)
        
        # define stack widget as a class property that is accessible within the class 
        self.stackedWidget = stackedWidget

        # 'Register here'  button event that switches the login page to register page
        self.btn_switch_register.clicked.connect(lambda: self.switch_to_register())
       
        # submit button click event hooking 
        self.submit_btn.clicked.connect(lambda: self.submit_form())


    
    # this function will be called when the submit button is clicked 
    def submit_form(self):
        self.submit_btn.setStyleSheet("QPushButton{\n"
                                        "    background-color: #EF9A53;\n"
                                        "    color: white;\n"
                                        "    border-style: outset;\n"
                                        "    border-width: 2px;\n"
                                        "    border-radius: 10px;\n"
                                        "    border-color: beige;\n"
                                        "    padding: 6px;\n"
                                        "}\n"
                                        "\n")

        # define the parameters of the http request
        PARAMS = {
                "password": self.pswd.text(),
                "id": self.id.text()      
        }
        URL = "http://localhost:8080/api/signIn"
        r = requests.post(url = URL, json=PARAMS)
        
        
        # Define the service name and account name to use for the JWT
        service_name = "myapp"
        account_name = "jwt"

        print(r.text)

        # Define the JWT value to store in the keyring
        response_json = json.loads(r.text)
        
        jwt_value = response_json["accessToken"]

        # Store the JWT in the keyring
        keyring.set_password(service_name, account_name, jwt_value)

        # switch to next page
        self.stackedWidget.setCurrentIndex(2)
   

    def switch_to_register(self):
        ''' this function switches to register page from login page''' 
        self.stackedWidget.setCurrentIndex(1)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
