# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_cards.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(796, 633)
        self.create_test_card = QtWidgets.QFrame(Form)
        self.create_test_card.setGeometry(QtCore.QRect(80, 100, 231, 410))
        self.create_test_card.setStyleSheet("QFrame{\n"
"    background-color: #2C2F33;\n"
"    color: beige;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 4px;\n"
"    border-color:beige;\n"
"    padding: 4px;\n"
"}")
        self.create_test_card.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.create_test_card.setFrameShadow(QtWidgets.QFrame.Raised)
        self.create_test_card.setObjectName("create_test_card")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.create_test_card)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_10 = QtWidgets.QLabel(self.create_test_card)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("URW Bookman [UKWN]")
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QFrame{\n"
"    border: 0px;\n"
"}")
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.timeLimit = QtWidgets.QTimeEdit(self.create_test_card)
        self.timeLimit.setObjectName("timeLimit")
        self.verticalLayout.addWidget(self.timeLimit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_9 = QtWidgets.QLabel(self.create_test_card)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("URW Bookman [UKWN]")
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QFrame{\n"
"    border: 0px;\n"
"}")
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.topic_2 = QtWidgets.QLineEdit(self.create_test_card)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topic_2.sizePolicy().hasHeightForWidth())
        self.topic_2.setSizePolicy(sizePolicy)
        self.topic_2.setStyleSheet("QLineEdit{\n"
"    color:white;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 1px solid rgb(170, 255, 0)  ;\n"
"}")
        self.topic_2.setObjectName("topic_2")
        self.verticalLayout.addWidget(self.topic_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label_12 = QtWidgets.QLabel(self.create_test_card)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("URW Bookman [UKWN]")
        font.setPointSize(15)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QFrame{\n"
"    border: 0px;\n"
"}")
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.subtopic_2 = QtWidgets.QLineEdit(self.create_test_card)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subtopic_2.sizePolicy().hasHeightForWidth())
        self.subtopic_2.setSizePolicy(sizePolicy)
        self.subtopic_2.setStyleSheet("QLineEdit{\n"
"    color:white;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 1px solid rgb(170, 255, 0)  ;\n"
"}")
        self.subtopic_2.setObjectName("subtopic_2")
        self.verticalLayout.addWidget(self.subtopic_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.label_13 = QtWidgets.QLabel(self.create_test_card)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("URW Bookman [UKWN]")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("QFrame{\n"
"    border: 0px;\n"
"}")
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.grade_2 = QtWidgets.QLineEdit(self.create_test_card)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grade_2.sizePolicy().hasHeightForWidth())
        self.grade_2.setSizePolicy(sizePolicy)
        self.grade_2.setStyleSheet("QLineEdit{\n"
"    color:white;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 1px solid rgb(170, 255, 0)  ;\n"
"}")
        self.grade_2.setObjectName("grade_2")
        self.verticalLayout.addWidget(self.grade_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.save_btn = QtWidgets.QPushButton(self.create_test_card)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.save_btn.setFont(font)
        self.save_btn.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: #FED049;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    padding: 6px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"        background-color: #7289DA;\n"
"        color: white;\n"
"}")
        self.save_btn.setObjectName("save_btn")
        self.verticalLayout.addWidget(self.save_btn)
        self.undo_btn = QtWidgets.QPushButton(self.create_test_card)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.undo_btn.setFont(font)
        self.undo_btn.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: #ff4b4b;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"        background-color: black;\n"
"        color: white;\n"
"}")
        self.undo_btn.setObjectName("undo_btn")
        self.verticalLayout.addWidget(self.undo_btn)
        self.test_card = QtWidgets.QFrame(Form)
        self.test_card.setGeometry(QtCore.QRect(380, 100, 245, 410))
        self.test_card.setStyleSheet("QFrame{\n"
"    background-color: #4b4b4b;\n"
"    color: beige;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 4px;\n"
"    border-color:beige;\n"
"    padding: 4px;\n"
"}")
        self.test_card.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.test_card.setFrameShadow(QtWidgets.QFrame.Raised)
        self.test_card.setObjectName("test_card")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.test_card)
        self.verticalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_12 = QtWidgets.QFrame(self.test_card)
        self.frame_12.setStyleSheet("color:beige;\n"
"background-color: #2D033B;\n"
"border: 1px solid beige;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.topic = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("URW Bookman [UKWN]")
        font.setPointSize(20)
        self.topic.setFont(font)
        self.topic.setStyleSheet("QFrame{\n"
"    border: 0px;\n"
"}")
        self.topic.setObjectName("topic")
        self.horizontalLayout_4.addWidget(self.topic, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.test_card)
        self.frame_13.setStyleSheet("border:1px solid beige;\n"
"background-color: #453C67;\n"
"color:black;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setStyleSheet("color:beige;\n"
"border: 0px solid beige;")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem5)
        self.grade = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("URW Bookman [UKWN]")
        font.setPointSize(17)
        self.grade.setFont(font)
        self.grade.setStyleSheet("border:0px;\n"
"")
        self.grade.setObjectName("grade")
        self.verticalLayout_7.addWidget(self.grade)
        self.verticalLayout_6.addWidget(self.frame_14)
        self.subtopic = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setFamily("URW Bookman [UKWN]")
        font.setPointSize(17)
        self.subtopic.setFont(font)
        self.subtopic.setStyleSheet("border:0px;\n"
"color:white;")
        self.subtopic.setObjectName("subtopic")
        self.verticalLayout_6.addWidget(self.subtopic)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.frame_15 = QtWidgets.QFrame(self.frame_13)
        self.frame_15.setStyleSheet("\n"
"border: 0px solid beige;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.start_btn = QtWidgets.QPushButton(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.start_btn.setFont(font)
        self.start_btn.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: #afafaf;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    padding: 6px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"        background-color: #7289DA;\n"
"        color: white;\n"
"}")
        self.start_btn.setObjectName("start_btn")
        self.verticalLayout_8.addWidget(self.start_btn)
        self.upload_btn = QtWidgets.QPushButton(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.upload_btn.setFont(font)
        self.upload_btn.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: #777777;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"        background-color: #FED049;\n"
"        color: white;\n"
"}")
        self.upload_btn.setObjectName("upload_btn")
        self.verticalLayout_8.addWidget(self.upload_btn)
        self.remove_btn = QtWidgets.QPushButton(self.frame_15)
        self.remove_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.remove_btn.setFont(font)
        self.remove_btn.setStyleSheet("QPushButton{\n"
"    background-color: #ff4b4b;\n"
"    color: black;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"        background-color: black;\n"
"        color: white;\n"
"}")
        self.remove_btn.setObjectName("remove_btn")
        self.verticalLayout_8.addWidget(self.remove_btn)
        self.verticalLayout_6.addWidget(self.frame_15)
        self.verticalLayout_5.addWidget(self.frame_13)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_10.setText(_translate("Form", "Time Limit"))
        self.label_9.setText(_translate("Form", "Topic "))
        self.label_12.setText(_translate("Form", "Sub-topic"))
        self.label_13.setText(_translate("Form", "Grade"))
        self.save_btn.setText(_translate("Form", "Save"))
        self.undo_btn.setText(_translate("Form", "Undo"))
        self.topic.setText(_translate("Form", "English"))
        self.grade.setText(_translate("Form", "Grade 11"))
        self.subtopic.setText(_translate("Form", "Present Simple"))
        self.start_btn.setText(_translate("Form", "Start"))
        self.upload_btn.setText(_translate("Form", "Upload"))
        self.remove_btn.setText(_translate("Form", "Remove"))


class TestCards(Ui_Form):
    def setupUi(self, Form, stackedWidget):
        super.setupUi(Form) 

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
