# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import resources
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1486, 691)
        Form.setStyleSheet("background-color:#001E6C;")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(560, 90, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(26)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;")
        self.label_3.setObjectName("label_3")
        self.frame_55 = QtWidgets.QFrame(Form)
        self.frame_55.setGeometry(QtCore.QRect(110, 180, 1231, 371))
        self.frame_55.setStyleSheet("QFrame{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    padding: 4px;    \n"
"    background-color: #035397;\n"
"    botder: 1px solid white;\n"
"}")
        self.frame_55.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_55.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_55.setObjectName("frame_55")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_55)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_7 = QtWidgets.QFrame(self.frame_55)
        self.frame_7.setStyleSheet("background-color: #2D033B;\n"
"color: white;\n"
"padding: 0px;\n"
"margin: 0px;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.frame_7)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(22)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("border: 0px;\n"
"padding: 0px;")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11, 0, QtCore.Qt.AlignHCenter)
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setStyleSheet("border: 0px;\n"
"background-color: #2D033B;\n"
"color: white;\n"
"padding: 0px;\n"
"margin: 0px;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_43 = QtWidgets.QFrame(self.frame_9)
        self.frame_43.setStyleSheet("border: 2px solid white;")
        self.frame_43.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_43.setObjectName("frame_43")
        self.gridLayout_5.addWidget(self.frame_43, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_9)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("border: 0px;\n"
"padding: 0px;")
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.frame_44 = QtWidgets.QFrame(self.frame_9)
        self.frame_44.setStyleSheet("border: 2px solid white;")
        self.frame_44.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_44.setObjectName("frame_44")
        self.gridLayout_5.addWidget(self.frame_44, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_9)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(15)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("border: 0px;\n"
"padding: 0px;")
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.frame_9)
        self.gridLayout.addWidget(self.frame_7, 0, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_55)
        self.frame_5.setStyleSheet("background-color: #2D033B;\n"
"color: white;\n"
"padding: 0px;\n"
"margin: 0px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(22)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border: 0px;\n"
"padding: 0px;")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setStyleSheet("border: 0px;\n"
"background-color: #2D033B;\n"
"color: white;\n"
"padding: 0px;\n"
"margin: 0px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_39 = QtWidgets.QFrame(self.frame_6)
        self.frame_39.setStyleSheet("border: 2px solid white;")
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.gridLayout_3.addWidget(self.frame_39, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border: 0px;\n"
"padding: 0px;")
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.frame_40 = QtWidgets.QFrame(self.frame_6)
        self.frame_40.setStyleSheet("border: 2px solid white;")
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.gridLayout_3.addWidget(self.frame_40, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border: 0px;\n"
"padding: 0px;")
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.gridLayout.addWidget(self.frame_5, 0, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(Form)
        self.label_37.setGeometry(QtCore.QRect(10, 10, 361, 51))
        font = QtGui.QFont()
        font.setFamily("FreeMono")
        font.setPointSize(22)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color: beige;\n"
"border: 1px solid beige;\n"
"padding: 6px;\n"
"color: white;\n"
"border-radius: 10px;")
        self.label_37.setObjectName("label_37")
        self.next_btn = QtWidgets.QPushButton(Form)
        self.next_btn.setGeometry(QtCore.QRect(1370, 320, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.next_btn.setFont(font)
        self.next_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.next_btn.setAutoFillBackground(False)
        self.next_btn.setStyleSheet("QPushButton{\n"
"    background-color: #035397;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:5px;\n"
"    border-color: beige;\n"
"    padding: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #7289DA;\n"
"}")
        self.next_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next_btn.setIcon(icon)
        self.next_btn.setIconSize(QtCore.QSize(170, 170))
        self.next_btn.setObjectName("next_btn")
        self.previous_btn = QtWidgets.QPushButton(Form)
        self.previous_btn.setGeometry(QtCore.QRect(20, 320, 71, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previous_btn.sizePolicy().hasHeightForWidth())
        self.previous_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.previous_btn.setFont(font)
        self.previous_btn.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.previous_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.previous_btn.setStyleSheet("QPushButton{\n"
"    background-color: #035397;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:5px;\n"
"    border-color: beige;\n"
"    padding: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #7289DA;\n"
"}")
        self.previous_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previous_btn.setIcon(icon1)
        self.previous_btn.setIconSize(QtCore.QSize(170, 170))
        self.previous_btn.setObjectName("previous_btn")
        self.flow_btn = QtWidgets.QPushButton(Form)
        self.flow_btn.setGeometry(QtCore.QRect(700, 590, 113, 39))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.flow_btn.setFont(font)
        self.flow_btn.setStyleSheet("QPushButton{\n"
"    background-color: #FED049;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"        background-color: #7289DA;\n"
"        color: white;\n"
"}")
        self.flow_btn.setObjectName("flow_btn")
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(1170, 150, 151, 17))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(1200, 120, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Teacher Panel"))
        self.label_11.setText(_translate("Form", "Harel Zeevi"))
        self.label_12.setText(_translate("Form", "Camera"))
        self.label_13.setText(_translate("Form", "Screenshot"))
        self.label_7.setText(_translate("Form", "Harel Zeevi"))
        self.label_6.setText(_translate("Form", "Camera"))
        self.label_5.setText(_translate("Form", "Screenshot"))
        self.label_37.setText(_translate("Form", "Time Left: 01:40:00"))
        self.flow_btn.setText(_translate("Form", "Flow "))
        self.label.setText(_translate("Form", "Velocity"))


class TestPanel:

    def __init__():
        
        # init list of client names
        self.names = []
        
    def setupUi(self, Form, stackedWidget=None):
        ''' this function gets the stacked widget and changes 
        the shown page according to the events in the page '''
        
        super().setupUi(Form)
        
        # define stack widget as a class property that is accessible within the class 
        self.stackedWidget = stackedWidget

        # This call opens a dianlog for saving the test document
        self.download_btn.clicked.connect(lambda: self.download_test())
    
        # 'next page'  button event that switches to next page 
        self.next_btn.clicked.connect(lambda: self.next_page())

        # 'previous page'  button event that switches to previous page 
        self.previous_btn.clicked.connect(lambda: self.previous_page())



    def next_page(self):
        ''' This function switches to the next existing page and shows it '''
        
        print("next")
  
        # if it is the last existing page (there's no next
        if len(self.names) - (self.page_num + 1) * 40 < 0:
            return 

        # increasing the number of the current page by 1 
        self.page_num = self.page_num + 1

        # init the new video streams in the slots
        self.update_streams()
        
        print("New Page: ", self.page_num)



    def previous_page(self):
        ''' This function switches to the previous existing page and shows it '''
        
        # if it is the first existing page (there's no previous)
        if self.page_num == 0:
            return

        # decreasing the number of the current page by 1 
        self.page_num = self.page_num - 1
        
        # init the new video streams in the slots
        self.update_streams()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
