# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/waiting_room_teacher_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import requests
import json
import keyring
from PyQt5 import QtCore, QtGui, QtWidgets
import resources

import sys
sys.path.append('./../socket/')
from tcp_teacher import TcpTeacher



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1712, 684)
        Form.setMinimumSize(QtCore.QSize(1712, 684))
        Form.setMaximumSize(QtCore.QSize(1712, 684))
        Form.setStyleSheet("background-color:#001E6C;")
        self.frame_5 = QtWidgets.QFrame(Form)
        self.frame_5.setGeometry(QtCore.QRect(130, 210, 1451, 311))
        font = QtGui.QFont()
        font.setFamily("Tlwg Typewriter")
        font.setBold(False)
        font.setWeight(50)
        self.frame_5.setFont(font)
        self.frame_5.setStyleSheet("QFrame{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 0px;\n"
"    border-color: black;\n"
"    padding: 10px;    \n"
"    background-color: #035397;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setObjectName("gridLayout")
        self.slot12 = QtWidgets.QLabel(self.frame_5)
        self.slot12.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot12.setFont(font)
        self.slot12.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot12.setObjectName("slot12")
        self.gridLayout.addWidget(self.slot12, 6, 3, 1, 1)
        self.slot3 = QtWidgets.QLabel(self.frame_5)
        self.slot3.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.slot3.setFont(font)
        self.slot3.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot3.setObjectName("slot3")
        self.gridLayout.addWidget(self.slot3, 0, 2, 1, 1)
        self.slot2 = QtWidgets.QLabel(self.frame_5)
        self.slot2.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.slot2.setFont(font)
        self.slot2.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot2.setObjectName("slot2")
        self.gridLayout.addWidget(self.slot2, 0, 1, 1, 1)
        self.slot37 = QtWidgets.QLabel(self.frame_5)
        self.slot37.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot37.setFont(font)
        self.slot37.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot37.setObjectName("slot37")
        self.gridLayout.addWidget(self.slot37, 20, 4, 1, 1)
        self.slot13 = QtWidgets.QLabel(self.frame_5)
        self.slot13.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot13.setFont(font)
        self.slot13.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot13.setObjectName("slot13")
        self.gridLayout.addWidget(self.slot13, 6, 4, 1, 1)
        self.slot29 = QtWidgets.QLabel(self.frame_5)
        self.slot29.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot29.setFont(font)
        self.slot29.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot29.setObjectName("slot29")
        self.gridLayout.addWidget(self.slot29, 19, 4, 1, 1)
        self.slot28 = QtWidgets.QLabel(self.frame_5)
        self.slot28.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot28.setFont(font)
        self.slot28.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot28.setObjectName("slot28")
        self.gridLayout.addWidget(self.slot28, 19, 3, 1, 1)
        self.slot14 = QtWidgets.QLabel(self.frame_5)
        self.slot14.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot14.setFont(font)
        self.slot14.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot14.setObjectName("slot14")
        self.gridLayout.addWidget(self.slot14, 6, 5, 1, 1)
        self.slot4 = QtWidgets.QLabel(self.frame_5)
        self.slot4.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.slot4.setFont(font)
        self.slot4.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot4.setObjectName("slot4")
        self.gridLayout.addWidget(self.slot4, 0, 3, 1, 1)
        self.slot11 = QtWidgets.QLabel(self.frame_5)
        self.slot11.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot11.setFont(font)
        self.slot11.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot11.setObjectName("slot11")
        self.gridLayout.addWidget(self.slot11, 6, 2, 1, 1)
        self.slot19 = QtWidgets.QLabel(self.frame_5)
        self.slot19.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot19.setFont(font)
        self.slot19.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot19.setObjectName("slot19")
        self.gridLayout.addWidget(self.slot19, 16, 2, 1, 1)
        self.slot32 = QtWidgets.QLabel(self.frame_5)
        self.slot32.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot32.setFont(font)
        self.slot32.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot32.setObjectName("slot32")
        self.gridLayout.addWidget(self.slot32, 19, 7, 1, 1)
        self.slot35 = QtWidgets.QLabel(self.frame_5)
        self.slot35.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot35.setFont(font)
        self.slot35.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot35.setObjectName("slot35")
        self.gridLayout.addWidget(self.slot35, 20, 2, 1, 1)
        self.slot21 = QtWidgets.QLabel(self.frame_5)
        self.slot21.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot21.setFont(font)
        self.slot21.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot21.setObjectName("slot21")
        self.gridLayout.addWidget(self.slot21, 16, 4, 1, 1)
        self.slot27 = QtWidgets.QLabel(self.frame_5)
        self.slot27.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot27.setFont(font)
        self.slot27.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot27.setObjectName("slot27")
        self.gridLayout.addWidget(self.slot27, 19, 2, 1, 1)
        self.slot34 = QtWidgets.QLabel(self.frame_5)
        self.slot34.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot34.setFont(font)
        self.slot34.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot34.setObjectName("slot34")
        self.gridLayout.addWidget(self.slot34, 20, 1, 1, 1)
        self.slot39 = QtWidgets.QLabel(self.frame_5)
        self.slot39.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot39.setFont(font)
        self.slot39.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot39.setObjectName("slot39")
        self.gridLayout.addWidget(self.slot39, 20, 6, 1, 1)
        self.slot6 = QtWidgets.QLabel(self.frame_5)
        self.slot6.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.slot6.setFont(font)
        self.slot6.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot6.setObjectName("slot6")
        self.gridLayout.addWidget(self.slot6, 0, 5, 1, 1)
        self.slot36 = QtWidgets.QLabel(self.frame_5)
        self.slot36.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot36.setFont(font)
        self.slot36.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot36.setObjectName("slot36")
        self.gridLayout.addWidget(self.slot36, 20, 3, 1, 1)
        self.slot7 = QtWidgets.QLabel(self.frame_5)
        self.slot7.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot7.setFont(font)
        self.slot7.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot7.setObjectName("slot7")
        self.gridLayout.addWidget(self.slot7, 0, 6, 1, 1)
        self.slot20 = QtWidgets.QLabel(self.frame_5)
        self.slot20.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot20.setFont(font)
        self.slot20.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot20.setObjectName("slot20")
        self.gridLayout.addWidget(self.slot20, 16, 3, 1, 1)
        self.slot16 = QtWidgets.QLabel(self.frame_5)
        self.slot16.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot16.setFont(font)
        self.slot16.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot16.setObjectName("slot16")
        self.gridLayout.addWidget(self.slot16, 6, 7, 1, 1)
        self.slot15 = QtWidgets.QLabel(self.frame_5)
        self.slot15.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot15.setFont(font)
        self.slot15.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot15.setObjectName("slot15")
        self.gridLayout.addWidget(self.slot15, 6, 6, 1, 1)
        self.slot8 = QtWidgets.QLabel(self.frame_5)
        self.slot8.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot8.setFont(font)
        self.slot8.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot8.setObjectName("slot8")
        self.gridLayout.addWidget(self.slot8, 0, 7, 1, 1)
        self.slot17 = QtWidgets.QLabel(self.frame_5)
        self.slot17.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot17.setFont(font)
        self.slot17.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot17.setObjectName("slot17")
        self.gridLayout.addWidget(self.slot17, 16, 0, 1, 1)
        self.slot30 = QtWidgets.QLabel(self.frame_5)
        self.slot30.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot30.setFont(font)
        self.slot30.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot30.setObjectName("slot30")
        self.gridLayout.addWidget(self.slot30, 19, 5, 1, 1)
        self.slot40 = QtWidgets.QLabel(self.frame_5)
        self.slot40.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot40.setFont(font)
        self.slot40.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot40.setObjectName("slot40")
        self.gridLayout.addWidget(self.slot40, 20, 7, 1, 1)
        self.slot24 = QtWidgets.QLabel(self.frame_5)
        self.slot24.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot24.setFont(font)
        self.slot24.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot24.setObjectName("slot24")
        self.gridLayout.addWidget(self.slot24, 16, 7, 1, 1)
        self.slot26 = QtWidgets.QLabel(self.frame_5)
        self.slot26.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot26.setFont(font)
        self.slot26.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot26.setObjectName("slot26")
        self.gridLayout.addWidget(self.slot26, 19, 1, 1, 1)
        self.slot1 = QtWidgets.QLabel(self.frame_5)
        self.slot1.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.slot1.setFont(font)
        self.slot1.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot1.setObjectName("slot1")
        self.gridLayout.addWidget(self.slot1, 0, 0, 1, 1)
        self.slot25 = QtWidgets.QLabel(self.frame_5)
        self.slot25.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot25.setFont(font)
        self.slot25.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot25.setObjectName("slot25")
        self.gridLayout.addWidget(self.slot25, 19, 0, 1, 1)
        self.slot33 = QtWidgets.QLabel(self.frame_5)
        self.slot33.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot33.setFont(font)
        self.slot33.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot33.setObjectName("slot33")
        self.gridLayout.addWidget(self.slot33, 20, 0, 1, 1)
        self.slot31 = QtWidgets.QLabel(self.frame_5)
        self.slot31.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot31.setFont(font)
        self.slot31.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot31.setObjectName("slot31")
        self.gridLayout.addWidget(self.slot31, 19, 6, 1, 1)
        self.slot9 = QtWidgets.QLabel(self.frame_5)
        self.slot9.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot9.setFont(font)
        self.slot9.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot9.setObjectName("slot9")
        self.gridLayout.addWidget(self.slot9, 6, 0, 1, 1)
        self.slot10 = QtWidgets.QLabel(self.frame_5)
        self.slot10.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot10.setFont(font)
        self.slot10.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot10.setObjectName("slot10")
        self.gridLayout.addWidget(self.slot10, 6, 1, 1, 1)
        self.slot18 = QtWidgets.QLabel(self.frame_5)
        self.slot18.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot18.setFont(font)
        self.slot18.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot18.setObjectName("slot18")
        self.gridLayout.addWidget(self.slot18, 16, 1, 1, 1)
        self.slot23 = QtWidgets.QLabel(self.frame_5)
        self.slot23.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot23.setFont(font)
        self.slot23.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot23.setObjectName("slot23")
        self.gridLayout.addWidget(self.slot23, 16, 6, 1, 1)
        self.slot5 = QtWidgets.QLabel(self.frame_5)
        self.slot5.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.slot5.setFont(font)
        self.slot5.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot5.setObjectName("slot5")
        self.gridLayout.addWidget(self.slot5, 0, 4, 1, 1)
        self.slot22 = QtWidgets.QLabel(self.frame_5)
        self.slot22.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot22.setFont(font)
        self.slot22.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot22.setObjectName("slot22")
        self.gridLayout.addWidget(self.slot22, 16, 5, 1, 1)
        self.slot38 = QtWidgets.QLabel(self.frame_5)
        self.slot38.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.slot38.setFont(font)
        self.slot38.setStyleSheet("color:black;\n"
"background-color:#FFAA4C;")
        self.slot38.setObjectName("slot38")
        self.gridLayout.addWidget(self.slot38, 20, 5, 1, 1)
        self.previous_btn = QtWidgets.QPushButton(Form)
        self.previous_btn.setGeometry(QtCore.QRect(30, 310, 71, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previous_btn.sizePolicy().hasHeightForWidth())
        self.previous_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.previous_btn.setFont(font)
        self.previous_btn.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.previous_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.previous_btn.setStyleSheet("QPushButton{\n"
"    background-color: #035397;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:5px;\n"
"    border-color: beige;\n"
"    padding: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #7289DA;\n"
"}")
        self.previous_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previous_btn.setIcon(icon)
        self.previous_btn.setIconSize(QtCore.QSize(170, 170))
        self.previous_btn.setObjectName("previous_btn")
        self.label_38 = QtWidgets.QLabel(Form)
        self.label_38.setGeometry(QtCore.QRect(20, 20, 281, 51))
        font = QtGui.QFont()
        font.setFamily("FreeMono")
        font.setPointSize(22)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("color: beige;\n"
"border: 1px solid beige;\n"
"padding: 6px;\n"
"color: white;\n"
"border-radius: 10px;")
        self.label_38.setObjectName("label_38")
        self.kick_btn = QtWidgets.QPushButton(Form)
        self.kick_btn.setGeometry(QtCore.QRect(790, 560, 101, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.kick_btn.setFont(font)
        self.kick_btn.setStyleSheet("QPushButton{\n"
"    background-color: #f80000;\n"
"    color: black;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"        background-color: black;\n"
"        color: white;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    border: 2px solid #f87c7c;\n"
"    background-color:#f83e3e;\n"
"    color: #f87c7c;\n"
"}\n"
"")
        self.kick_btn.setObjectName("remove_btn")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(630, 60, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(26)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;")
        self.label_3.setObjectName("label_3")
        self.next_btn = QtWidgets.QPushButton(Form)
        self.next_btn.setGeometry(QtCore.QRect(1610, 320, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.next_btn.setFont(font)
        self.next_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.next_btn.setAutoFillBackground(False)
        self.next_btn.setStyleSheet("QPushButton{\n"
"    background-color: #035397;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:5px;\n"
"    border-color: beige;\n"
"    padding: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #7289DA;\n"
"}")
        self.next_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next_btn.setIcon(icon1)
        self.next_btn.setIconSize(QtCore.QSize(170, 170))
        self.next_btn.setObjectName("next_btn")
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.start_btn = QtWidgets.QPushButton(Form)
        self.start_btn.setGeometry(QtCore.QRect(640, 560, 121, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.start_btn.setFont(font)
        self.start_btn.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    background-color: #282A3A;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    padding: 6px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"        background-color: #7289DA;\n"
"        color: white;\n"
"}")
        self.start_btn.setObjectName("submit_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_38.setText(_translate("Form", "Token: aBdk3hy"))
        self.kick_btn.setText(_translate("Form", "kick"))
        self.label_3.setText(_translate("Form", "Waiting Room "))
        self.start_btn.setText(_translate("Form", "start"))



class WaitingRoomTeacher(Ui_Form, ):
    def __init__(self):

        # init empty student names list 
        self.names = []

        # amount of students per page
        self.NUM_SLOTS = 40
        
        # page number 
        self.page_num = 0

        # are students removable?
        self.removable = False


    def setupUi(self, Form, stackedWidget=None):
        ''' this function gets the stacked widget and changes 
        the shown page according to the events in the page '''
         
        super().setupUi(Form)
        
        self.stackedWidget = stackedWidget

        
        # 'kick btn' event that kicks a student out of the waiting room
        self.kick_btn.clicked.connect(lambda: self.kick_student())

        # 'next page'  button event that switches to next page 
        self.next_btn.clicked.connect(lambda: self.next_page())

        # 'previous page'  button event that switches to previous page 
        self.previous_btn.clicked.connect(lambda: self.previous_page())



    def next_page(self):
        ''' This function switches to the next existing page and shows it '''
        
        print("next")

        # reset removable state if it was clicked for new page
        if self.removable: 
            self.removable = not self.removable
      
        # if it is the last existing page (there's no next
        if len(self.names) - (self.page_num + 1) * 40 < 0:
            return 

        # increasing the number of the current page by 1 
        self.page_num = self.page_num + 1

        # init the new names in the slots
        self.update_names()
        
        print("New Page: ", self.page_num)



    def previous_page(self):
        ''' This function switches to the previous existing page and shows it '''
        
        # reset removable state if it was clicked for new page
        if self.removable: 
            self.removable = not self.removable
      

        # if it is the first existing page (there's no previous)
        if self.page_num == 0:
            return

        # decreasing the number of the current page by 1 
        self.page_num = self.page_num - 1
        
        print("New Page: ", self.page_num)

        # init the new names in the slots
        self.update_names()


    
    def update_names(self):
        ''' This function updates the gui of the names 
        of the students that are in the waiting room panel'''
        
        for i in range(self.NUM_SLOTS):


            label = eval(f'self.slot{i + 1}')

            # determine the index of the name 
            name_ind = self.page_num * 40 + i
            
            # if the index is valid 
            if name_ind < len(self.names):
                label.setStyleSheet("border-width:2px;\n"
                "background-color:#FFAA4C;")

                label.setText(self.names[name_ind])

            # no more names to put
            else:
                label.setStyleSheet("background-color: #035397;\n border-width:0px")
                label.setText("")
        


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = WaitingRoomTeacher()
    ui.setupUi(Form)
    ui.update_names()
    Form.show()
    sys.exit(app.exec_())
